version: '3.4'
name: trivia_backend_container

services:
  triviasecurityapi:
    image: ${DOCKER_REGISTRY-}triviasecurityapi
    ports:
        - 44312:8081
    build:
      context: TriviaSecurityApi
      dockerfile: Dockerfile
  triviacontestapi:
    image: ${DOCKER_REGISTRY-}triviacontestapi
    ports:
        - 44313:8081
    build:
      context: TriviaContestApi
      dockerfile: Dockerfile
  triviaratingapi:
    image: ${DOCKER_REGISTRY-}triviaratingapi
    ports:
        - 44314:8081
    build:
      context: TriviaRatingApi
      dockerfile: Dockerfile
