version: '3.4'
name: bilgiligi_backend_container

services:
  bilgiligisecurityapi:
    image: ${DOCKER_REGISTRY-}bilgiligisecurityapi
    expose:
        - "8080"
    build:
      context: BilgiLigiSecurityApi
      dockerfile: Dockerfile
    networks: 
        - backend-network
  bilgiligicontestapi:
    image: ${DOCKER_REGISTRY-}bilgiligicontestapi
    expose:
        - "8080"
    build:
      context: BilgiLigiContestApi
      dockerfile: Dockerfile
    networks: 
        - backend-network
  bilgiligiratingapi:
    image: ${DOCKER_REGISTRY-}bilgiligiratingapi
    expose:
        - "8080"
    build:
      context: BilgiLigiRatingApi
      dockerfile: Dockerfile
    networks: 
        - backend-network
  bilgiligicontributionapi:
    image: ${DOCKER_REGISTRY-}bilgiligiicontributionapi
    expose:
        - "8080"
    build:
      context: BilgiLigiContributionApi
      dockerfile: Dockerfile
    networks: 
        - backend-network
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    ports:
       - 44311:8080
    build:
      context: ApiGateway
      dockerfile: Dockerfile
    depends_on:
      - bilgiligisecurityapi
      - bilgiligicontestapi
      - bilgiligiratingapi
      - bilgiligicontributionapi
    networks: 
        - backend-network
networks:
     backend-network:

     